spring:
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1800000
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:rinha}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123}

server:
  tomcat:
    connection-timeout: 6000